=== varvind7/HospitalPortal/doctors.xsd
<schema targetNamespace="http://www.docinfo.com"
	xmlns="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<element name="doctors">
		<complexType>
			<sequence>
				<element name="doctor" minOccurs="0" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="name" type="string"/>
							<element name="email" type="string"/>
							<element name="dept" type="string"/>
							<element name="mobile">
								<simpleType>
									<restriction base="int">
										<pattern value="[0-9]{10}"/>
									</restriction>
								</simpleType>
							</element>
							<element name="qual" type="string" minOccurs="1" maxOccurs="unbounded"/>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>

</schema>

=== varvind7/HospitalPortal/ajax/new/doctors1.xml
<doctors
	xmlns="http://www.docinfo.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.docinfo.com C://Users/varvi/Desktop/html/new/doctors.xsd"
	>
	<doctor id='101'>
		<name>Arvind</name>
		<email>varvind7@gmail.com</email>
		<dept>Ortho</dept>
		<mobile>745745</mobile>
		<qual>MBBS</qual>
	</doctor>
	<doctor id='102'>
		<name>Ram</name>
		<email>ram7@gmail.com</email>
		<dept>ENT</dept>
		<mobile>7457445</mobile>
		<qual>MBBS</qual>
	</doctor>
	<doctor id='103'>
		<name>Hari</name>
		<email>hari@gmail.com</email>
		<dept>general</dept>
		<mobile>7457454</mobile>
		<qual>MBBS</qual>
		<qual>MS</qual>
	</doctor>
</doctors>
